// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Mark Ballereau",
            "email": "mark.ballereau@etu.uca.fr"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/songs/{song_id}/ratings": {
            "get": {
                "description": "Get song ratings.",
                "tags": [
                    "ratings"
                ],
                "summary": "Get song ratings.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Song UUID formatted ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Rating"
                            }
                        }
                    },
                    "422": {
                        "description": "Cannot parse id"
                    },
                    "500": {
                        "description": "Something went wrong"
                    }
                }
            },
            "post": {
                "description": "Post a song rating.",
                "tags": [
                    "ratings"
                ],
                "summary": "Post a song rating.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Song UUID formatted ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "rating request",
                        "name": "ratingRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RatingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Rating"
                        }
                    },
                    "422": {
                        "description": "rating must be between 0 and 5"
                    },
                    "500": {
                        "description": "Something went wrong"
                    }
                }
            }
        },
        "/songs/{song_id}/ratings/{rating_id}": {
            "get": {
                "description": "Get a song rating.",
                "tags": [
                    "ratings"
                ],
                "summary": "Get a song rating.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Song UUID formatted ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating UUID formatted ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Rating"
                        }
                    },
                    "404": {
                        "description": "Rating not found"
                    },
                    "422": {
                        "description": "Cannot parse id"
                    },
                    "500": {
                        "description": "Something went wrong"
                    }
                }
            },
            "put": {
                "description": "Modify a song rating.",
                "tags": [
                    "ratings"
                ],
                "summary": "Modify a song rating.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Song UUID formatted ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating UUID formatted ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "rating request",
                        "name": "ratingRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.RatingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Rating"
                        }
                    },
                    "404": {
                        "description": "rating not found"
                    },
                    "422": {
                        "description": "rating must be between 0 and 5"
                    },
                    "500": {
                        "description": "Something went wrong"
                    }
                }
            },
            "delete": {
                "description": "Delete a song rating.",
                "tags": [
                    "ratings"
                ],
                "summary": "Delete a song rating.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Song UUID formatted ID",
                        "name": "song_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rating UUID formatted ID",
                        "name": "rating_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Cannot parse id"
                    },
                    "500": {
                        "description": "Something went wrong"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Rating": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "rating_date": {
                    "type": "string"
                },
                "song_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "models.RatingRequest": {
            "type": "object",
            "properties": {
                "comment": {
                    "type": "string"
                },
                "rating": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Ratings API",
	Description:      "API to manage ratings.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
